### ISSUE TITLE
DLL Issues

### ISSUE THREAD

**Issue by leezbtv** [ErikBongers/streamdeck-lightroom#8]
On a Windows 10 Pro 64-bit installation running current versions of Lighroom and El Gato software trying to set up the plug-in results in errors for the following 3 DLLs missing:
MSVCP140D.dll
VCRUNTIME140D.dll
ucrtbased.dll

I've tried setting up and installing different versions of the Visual C++ redistributibles and still have the same errors. A couple forum posts suggest that the "d" at the end of each of those DLLs means the tool is looking for a development version and not a development version of your too.  I've seen at least one other user on Reddit report this error as well.

I'm excited for this tool! Would love to have it working!

**Comment by ErikBongers** [comment]
Hi, I replaced the lr.exe, which was compiled in debug mode, with a release version.
Could you try that one?

**Comment by leezbtv** [comment]
This resolved it!  Works like a charm. Thanks Erik!

**Comment by ErikBongers** [comment]
Glad to hear :) 
Closes #8.
